oauth2_server.oauth2_server_scope.*:
  type: config_entity
  label: 'Scope config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
