oauth2_server.oauth2_server_scope.*:
  type: config_entity
  label: 'Scope config'
  mapping:
    id:
      type: string
      label: 'ID'
    server:
      type: label
      label: 'Server'
    name:
      type: string
      label: 'name'
    description:
      type: string
      label: 'description'
    uuid:
      type: string
