# Schema for OAuth2 scope.

oauth2_server.scope.*:
  type: config_object
  label: 'OAuth2 Scope settings'
  mapping:
    server:
      type: string
      label: 'The {oauth2_server}.name of the parent server.'
    name:
      type: string
      label: 'The machine name of the scope'
    description:
      type: string
      label: 'The description used to describe the scope on the authorization form.'
