oauth2_server.scope.*:
  type: config_entity
  label: 'The OAuth2 Scope config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
